/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Term1.h
**     Project     : ProcessorExpert
**     Processor   : MKL46Z256VMC4
**     Component   : Term
**     Version     : Component 02.061, Driver 03.22, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-10-27, 20:57, # CodeGen: 2
**     Abstract    :
**This components generates low-level console IO routines for selected UART.
**     Settings    :
**
**     Contents    :
**         CRLF       - void Term1_CRLF(void);
**         SendStr    - void Term1_SendStr(uint8_t *str);
**         SendNum    - void Term1_SendNum(int32_t number);
**         SendChar   - void Term1_SendChar(char_t Val);
**         Cls        - void Term1_Cls(void);
**         MoveTo     - void Term1_MoveTo(uint8_t x, uint8_t y);
**         ReadChar   - void Term1_ReadChar(char_t *c);
**         KeyPressed - bool Term1_KeyPressed(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file Term1.h
** @version 03.22
** @brief
**This components generates low-level console IO routines for selected UART.
*/         
/*!
**  @addtogroup Term1_module Term1 module documentation
**  @{
*/         

#ifndef __Term1
#define __Term1

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/* MODULE Term1. */

#include "Cpu.h"


void Term1_SendChar(char_t Val);
/*
** ===================================================================
**     Method      :  Term1_SendChar (component Term)
**     Description :
**         Send char to terminal.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Val             - Char to send
**     Returns     : Nothing
** ===================================================================
*/

void Term1_ReadChar(char_t *c);
/*
** ===================================================================
**     Method      :  Term1_ReadChar (component Term)
**     Description :
**         Read char from terminal.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * c               - Pointer to a char variable
**     Returns     : Nothing
** ===================================================================
*/

bool Term1_KeyPressed(void);
/*
** ===================================================================
**     Method      :  Term1_KeyPressed (component Term)
**     Description :
**         Test if char was received from the terminal.
**     Parameters  : None
**     Returns     :
**         ---             - Return <true> if user pressed some key
** ===================================================================
*/

void Term1_CRLF(void);
/*
** ===================================================================
**     Method      :  Term1_CRLF (component Term)
**     Description :
**         Send CRLF to terminal.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Term1_SendStr(void *str);
/*
** ===================================================================
**     Method      :  Term1_SendStr (component Term)
**     Description :
**         Send string to terminal.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to a string variable
**     Returns     : Nothing
** ===================================================================
*/

void Term1_SendNum(int32_t number);
/*
** ===================================================================
**     Method      :  Term1_SendNum (component Term)
**     Description :
**         Send number to terminal.
**     Parameters  :
**         NAME            - DESCRIPTION
**         number          - Long number
**     Returns     : Nothing
** ===================================================================
*/

void Term1_Cls(void);
/*
** ===================================================================
**     Method      :  Term1_Cls (component Term)
**     Description :
**         Clear the terminal window.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void Term1_MoveTo(uint8_t x,uint8_t y);
/*
** ===================================================================
**     Method      :  Term1_MoveTo (component Term)
**     Description :
**         Move cursor to position x, y. Range of coordinates can be
**         from 1 to the size, which depends on the used terminal.
**         Position [1,1] represents the upper left corner.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - Column number
**         y               - Row number
**     Returns     : Nothing
** ===================================================================
*/


/* END Term1. */

#endif /* ifndef __Term1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
