/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : S1_Cadera_Aduccion.c
**     Project     : ProcessorExpert
**     Processor   : MKL46Z256VMC4
**     Component   : BitIO
**     Version     : Component 02.086, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-11-15, 16:44, # CodeGen: 20
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       90            |  LCD_P30/PTC10/I2C1_SCL/I2S0_RX_FS
**             ----------------------------------------------------
**
**         Port name                   : PTC
**
**         Bit number (in port)        : 10
**         Bit mask of the port        : 0x0400
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : GPIOC_PDOR [0x400FF080]
**         Port control register       : GPIOC_PDDR [0x400FF094]
**
**         Optimization for            : speed
**     Contents    :
**         SetDir - void S1_Cadera_Aduccion_SetDir(bool Dir);
**         GetVal - bool S1_Cadera_Aduccion_GetVal(void);
**         PutVal - void S1_Cadera_Aduccion_PutVal(bool Val);
**         ClrVal - void S1_Cadera_Aduccion_ClrVal(void);
**         SetVal - void S1_Cadera_Aduccion_SetVal(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file S1_Cadera_Aduccion.c
** @version 01.00
** @brief
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
*/         
/*!
**  @addtogroup S1_Cadera_Aduccion_module S1_Cadera_Aduccion module documentation
**  @{
*/         

/* MODULE S1_Cadera_Aduccion. */

#include "S1_Cadera_Aduccion.h"

#ifdef __cplusplus
extern "C" {
#endif 

/*
** ===================================================================
**     Method      :  S1_Cadera_Aduccion_SetDir (component BitIO)
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
/*
void S1_Cadera_Aduccion_SetDir(bool Dir)

**  This method is implemented as a macro. See S1_Cadera_Aduccion.h file.  **
*/

/*
** ===================================================================
**     Method      :  S1_Cadera_Aduccion_GetVal (component BitIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool S1_Cadera_Aduccion_GetVal(void)

**  This method is implemented as a macro. See S1_Cadera_Aduccion.h file.  **
*/

/*
** ===================================================================
**     Method      :  S1_Cadera_Aduccion_PutVal (component BitIO)
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
/*
void S1_Cadera_Aduccion_PutVal(bool Val)

**  This method is implemented as a macro. See S1_Cadera_Aduccion.h file.  **
*/

/*
** ===================================================================
**     Method      :  S1_Cadera_Aduccion_ClrVal (component BitIO)
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void S1_Cadera_Aduccion_ClrVal(void)

**  This method is implemented as a macro. See S1_Cadera_Aduccion.h file.  **
*/

/*
** ===================================================================
**     Method      :  S1_Cadera_Aduccion_SetVal (component BitIO)
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void S1_Cadera_Aduccion_SetVal(void)

**  This method is implemented as a macro. See S1_Cadera_Aduccion.h file.  **
*/

/* END S1_Cadera_Aduccion. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
